### ISSUE TITLE
Add On Hand tracking

### ISSUE THREAD

**Issue by SchmidtCode** [SchmidtCode/IMSim#5]
- [ ] Store Order Data (Lead Time for when it arrives)
- [ ] Track On Hand Quantity
- [ ] Create graph of On Hand Quantity
